#!/bin/bash

export EXECUTION_MODE="paper"
export ENABLE_TELEGRAM="0"
export SEND_TELEGRAM="0"
export DASHBOARD_HOST="127.0.0.1"
export DASHBOARD_PORT="${DASHBOARD_PORT:-3006}"
export STRATEGY_CONFIG_FILE_PATH="$ROOT_DIR/runtime/strategy-config.btc-gated-bearish-lab.json"
export STRATEGY_GENERATED_CONFIG_FILE_PATH="$ROOT_DIR/runtime/strategy-config.generated.btc-gated-bearish-lab.json"
export ADAPTIVE_CONFIG_FILE_PATH="$ROOT_DIR/runtime/adaptive-config.btc-gated-bearish-lab.json"
export STATE_FILE_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/state.json"
export ORDERS_LOG_FILE_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/orders-log.json"
export EXECUTION_METRICS_FILE_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/execution-metrics.json"
export PERFORMANCE_BASELINE_FILE_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/performance-baseline.json"
export ADAPTIVE_HISTORY_FILE_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/adaptive-history.json"
export RESEARCH_JSON_FILE_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/consolidated-trades.json"
export RESEARCH_CSV_FILE_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/consolidated-trades.csv"
export SQLITE_DB_PATH="$ROOT_DIR/runtime/btc-gated-bearish-lab/runtime-store.sqlite"
export BOT_STATUS_SCRIPT_PATH="$ROOT_DIR/botstatus-btc-gated-bearish-lab.js"
export BOT_START_SCRIPT_PATH="$ROOT_DIR/botstart-btc-gated-bearish-lab.js"
export BOT_STOP_SCRIPT_PATH="$ROOT_DIR/botstop-btc-gated-bearish-lab.js"
