#!/bin/bash

export STRATEGY_HUNT_PROFILE_NAME="broad"
export STRATEGY_HUNT_SYMBOLS="${STRATEGY_HUNT_BROAD_SYMBOLS:-BTCUSDC,ETHUSDC,ADAUSDC,LINKUSDC,1000SHIBUSDC,1000PEPEUSDC,SOLUSDC,XRPUSDC,BNBUSDC,DOGEUSDC,LTCUSDC,BCHUSDC}"
export STRATEGY_HUNT_TFS="${STRATEGY_HUNT_BROAD_TFS:-15m,1h}"
export STRATEGY_HUNT_HTF_TF="${STRATEGY_HUNT_BROAD_HTF_TF:-1d}"
export STRATEGY_HUNT_OUTPUT_DIR="${STRATEGY_HUNT_BROAD_OUTPUT_DIR:-$ROOT_DIR/research/cache/server-strategy-hunts/broad}"
export BACKTEST_LTF_LIMIT="${STRATEGY_HUNT_BROAD_LTF_LIMIT:-2200}"
export BACKTEST_HTF_LIMIT="${STRATEGY_HUNT_BROAD_HTF_LIMIT:-360}"
export STRATEGY_HUNT_LOADAVG_MAX="${STRATEGY_HUNT_BROAD_LOADAVG_MAX:-1.90}"
export STRATEGY_HUNT_MEM_AVAILABLE_MB_MIN="${STRATEGY_HUNT_BROAD_MEM_AVAILABLE_MB_MIN:-1200}"
export STRATEGY_HUNT_BUILD_REGISTRY="${STRATEGY_HUNT_BROAD_BUILD_REGISTRY:-1}"
