#!/bin/bash

export STRATEGY_HUNT_SYMBOLS="${STRATEGY_HUNT_SYMBOLS:-BTCUSDC,ETHUSDC,ADAUSDC,LINKUSDC,1000SHIBUSDC,1000PEPEUSDC,SOLUSDC,XRPUSDC,BNBUSDC,DOGEUSDC,LTCUSDC,BCHUSDC,AVAXUSDT,SUIUSDT,NEARUSDT,ARBUSDT,APTUSDT,OPUSDT,FETUSDT,INJUSDT,SEIUSDT,UNIUSDT,ATOMUSDT,AAVEUSDT,FILUSDT,TRXUSDT,TONUSDT}"
export STRATEGY_HUNT_TFS="${STRATEGY_HUNT_TFS:-15m,1h}"
export STRATEGY_HUNT_HTF_TF="${STRATEGY_HUNT_HTF_TF:-1d}"
export STRATEGY_HUNT_OUTPUT_DIR="${STRATEGY_HUNT_OUTPUT_DIR:-$ROOT_DIR/research/cache/server-strategy-hunts}"
export BACKTEST_FEE_RATE="${BACKTEST_FEE_RATE:-0.0004}"
export BACKTEST_SLIPPAGE_PCT="${BACKTEST_SLIPPAGE_PCT:-0.00025}"
export BACKTEST_LTF_LIMIT="${BACKTEST_LTF_LIMIT:-3000}"
export BACKTEST_HTF_LIMIT="${BACKTEST_HTF_LIMIT:-400}"
