#!/bin/bash

export STRATEGY_HUNT_PROFILE_NAME="narrow"
export STRATEGY_HUNT_SYMBOLS="${STRATEGY_HUNT_NARROW_SYMBOLS:-BTCUSDC,ETHUSDC,SOLUSDC,XRPUSDC,1000PEPEUSDC}"
export STRATEGY_HUNT_ROTATION_BLOCKS="${STRATEGY_HUNT_NARROW_ROTATION_BLOCKS:-BTCUSDC,ETHUSDC,SOLUSDC,XRPUSDC|1000PEPEUSDC,BNBUSDC,DOGEUSDC,LTCUSDC|BCHUSDC,LINKUSDC,ADAUSDC,1000SHIBUSDC}"
export STRATEGY_HUNT_ROTATION_STATE_FILE="${STRATEGY_HUNT_NARROW_ROTATION_STATE_FILE:-$ROOT_DIR/runtime/strategy-hunt-narrow-rotation.json}"
export STRATEGY_HUNT_TFS="${STRATEGY_HUNT_NARROW_TFS:-15m,1h}"
export STRATEGY_HUNT_HTF_TF="${STRATEGY_HUNT_NARROW_HTF_TF:-1d}"
export STRATEGY_HUNT_OUTPUT_DIR="${STRATEGY_HUNT_NARROW_OUTPUT_DIR:-$ROOT_DIR/research/cache/server-strategy-hunts/narrow}"
export BACKTEST_LTF_LIMIT="${STRATEGY_HUNT_NARROW_LTF_LIMIT:-1800}"
export BACKTEST_HTF_LIMIT="${STRATEGY_HUNT_NARROW_HTF_LIMIT:-320}"
export STRATEGY_HUNT_LOADAVG_MAX="${STRATEGY_HUNT_NARROW_LOADAVG_MAX:-2.40}"
export STRATEGY_HUNT_MEM_AVAILABLE_MB_MIN="${STRATEGY_HUNT_NARROW_MEM_AVAILABLE_MB_MIN:-900}"
export STRATEGY_HUNT_BUILD_REGISTRY="${STRATEGY_HUNT_NARROW_BUILD_REGISTRY:-1}"
